name = "My Fabric Modpack"
author = "samer"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1aa39a8c8888c5e4dc9176647fc294c3ee72c9feb42238fea5e85bf156f5828c"

[versions]
fabric = "0.16.10"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
